version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.9-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install dependencies in a python venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths: 
            - "venv"

workflows:
  version: 2
  build-test:
    jobs:
      - build 
      - test:
          context:
            - back_final
          requires: 
            - build