version: 2
jobs:
  build:
    docker: 
      - image: python:3.8-buster
    working_directory: ~/back
    steps: 
      - checkout
      - restore_cache:
          key: deps9-{{ checksum "Pipfile.lock" }}
      - run: 
          name: set env vars
          command: | 
            export CONDUIT_SECRET='something-secret'
            export FLASK_APP=./autoapp.py
            export FLASK_DEBUG=1
      - run : 
          name: install deps
          command: |
            /usr/local/bin/python -m pip install --upgrade pip
            apk update && apk add postgresql-dev gcc python3-dev musl-dev
            pip install -r requirements/dev.txt --user
            pip install Flask
      - save_cache:
          key: deps9-{{ checksum "Pipfile.lock" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
  test:
    docker: 
      - image: python:3.8-buster
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: myUsr
          POSTGRES_DB: psdb
          POSTGRES_PASSWORD: somePwd
          DATABASE_URL: postgresql://myUsr:$POSTGRES_PASSWORD@localhost:5432/$POSTGRES_USER
    steps:
      - checkout
      - restore_cache:
          key: deps9-{{ checksum "Pipfile.lock" }}
      - run:
          name : test
          command: |
            flask db upgrade
            flask test
            unset DATABASE_URL

workflows:
  version: 2
  build-test:
    jobs:
      - build 
      - test:
          context:
            - back_final
          requires: 
            - build